name := "samba"
packages := "
samba
samba-client
"
version_package := "samba"
base_images := "
ghcr.io/ublue-os/cayo:10 x86_64
ghcr.io/ublue-os/cayo:42 x86_64
"

import '../sysext.just'

all: default
