name := "docker-ce"
packages := "
docker-ce
docker-ce-cli
containerd.io
docker-buildx-plugin
docker-compose-plugin
"
upholds := "
docker.socket
"
files := "usr"
external_repos := "https://download.docker.com/linux/centos/docker-ce.repo"
base_images := "
ghcr.io/ublue-os/cayo:10 x86_64
ghcr.io/ublue-os/cayo:42 x86_64
"

import '../sysext.just'

all: default
