name: "Build sysexts for Centos"

env:
  GH_TOKEN: ${{ github.token }}
  RELEASEURL: "https://github.com/${{ github.repository }}/releases/download"

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
    inputs:
      force-rebuild:
        description: 'Force rebuild of all sysexts'
        required: true
        default: false
        type: boolean

# Needed to allow creating a release
permissions:
  contents: write

# Prevent multiple workflow runs from racing to ensure that pushes are made
# sequentialy for the main branch. Also cancel in progress workflow runs.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-${{ inputs.sysext }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-centos-10-x86_64:
    runs-on: "ubuntu-24.04"
    container:
      image: "ghcr.io/bketelsen/cayo-sysexts/buildroot:latest"
      options: "--privileged --security-opt label=disable --user 0:0"
    env:
      IMAGE: "ghcr.io/ublue-os/cayo:10"
      FORCE_REBUILD: ${{ inputs.force-rebuild }}
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4

      - name: "Setup artifacts and dnf cache directories"
        run: |
          mkdir -p artifacts .dnf-cache

      - name: "Mark directory as safe"
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main

      - name: "Build sysext: docker-ce"
        uses: ./.github/actions/build
        with:
          sysext: 'docker-ce'
          image: ${{ env.IMAGE }}

      - name: "Build sysext: samba"
        uses: ./.github/actions/build
        with:
          sysext: 'samba'
          image: ${{ env.IMAGE }}

      - name: "Build sysext: vim"
        uses: ./.github/actions/build
        with:
          sysext: 'vim'
          image: ${{ env.IMAGE }}

  build-fedora-42-x86_64:
    runs-on: "ubuntu-24.04"
    container:
      image: "ghcr.io/bketelsen/cayo-sysexts/buildroot:latest"
      options: "--privileged --security-opt label=disable --user 0:0"
    env:
      IMAGE: "ghcr.io/ublue-os/cayo:42"
      FORCE_REBUILD: ${{ inputs.force-rebuild }}
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4

      - name: "Setup artifacts and dnf cache directories"
        run: |
          mkdir -p artifacts .dnf-cache

      - name: "Mark directory as safe"
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main

      - name: "Build sysext: docker-ce"
        uses: ./.github/actions/build
        with:
          sysext: 'docker-ce'
          image: ${{ env.IMAGE }}

      - name: "Build sysext: samba"
        uses: ./.github/actions/build
        with:
          sysext: 'samba'
          image: ${{ env.IMAGE }}

      - name: "Build sysext: vim"
        uses: ./.github/actions/build
        with:
          sysext: 'vim'
          image: ${{ env.IMAGE }}

  publish-sysexts:
    runs-on: "ubuntu-24.04"
    container:
      image: "ghcr.io/bketelsen/cayo-sysexts/buildroot:latest"
      options: "--privileged --security-opt label=disable --user 0:0"
    # Run after the builds and versionned release
    needs:
      - build-centos-10-x86_64
      - build-fedora-42-x86_64

    # Use `always()` to still run if any dependent job fails
    if: ${{ always() && (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main' }}
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4

      - name: "Mark directory as safe"
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main

      - name: "Gather all sysexts releases"
        uses: ./.github/actions/gather
        with:
          sysexts: 'docker-ce;samba;vim;'
